[package]
name = "sqshell"
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
anyhow = "1.0.70"
base64 = "0.21.0"
clap = { version = "4.2.1", features = ["derive", "cargo"] }
home = "0.5.4"
rusqlite = "0.29.0"
rustyline = "11.0.0"
tabled = "0.10.0"
tracing-subscriber = "0.3.16"
